name: netToTo

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          set -x
          curl ifconfig.me
          pwd
          touch ./m1
          echo "${{ secrets.M1 }}" > ./m1
          ls -lha
          sudo chmod 400 ./m1
          sudo docker run -itd --name squid  -v "`pwd`/squid.conf:/etc/squid/squid.conf" -p 3128:3128  docker.io/ubuntu/squid
          ssh  -i ./m1  -N -f -g -o ServerAliveInterval=60 -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -R 3128:localhost:3128  root@60.204.247.75
          num=`cat push.event`
          for i in `seq $num`
          do
            echo $i
            sleep 1
          done

          docker stop squid
          docker rm squid

          ps aux |grep ssh|awk '{print $2}'|xargs  kill -9

          exit 0
