name: netToTo

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          set -x
          pwd
          touch ./m1
          echo "${{ secrets.M1 }}" > ./m1
          sudo ls -lha
          sudo chmod 400 ./m1

            
          ssh-keygen  -t rsa -f ./testrsa -P ''
          sudo mkdir -p  /root/.ssh
          sudo ls -lh /root/.ssh

          sudo cat testrsa.pub >> /root/.ssh/authorized_keys
          sudo chmod 600 /root/.ssh/authorized_keys

          sudo ssh  -N -f -g -o ServerAliveInterval=60 -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -i ./testrsa -D 9999 root@localhost 
